dekher/accounts/urls.py
from . import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('signin/', views.sign_in, name="sign_in"),
    path('register/', views.register, name="register"),
    path('logout/', views.log_out, name="log_out"),

    path('profile/<user_name>', views.profile_view, name="profile_view"),
    path('profile/update/<user_name>', views.update_profile, name="update_profile"),
]

dekher/dekher/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('funds/', include('fund.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dekher/fund/urls.py
from . import views
from django.urls import path

app_name = 'fund'

urlpatterns = [
    path('add/', views.add_fund, name='add_fund'),
    path('complete/<fund_id>', views.complete_fund, name='complete_fund'),
    path('<fund_id>/details/', views.fund_details, name='fund_details'),

    path('update/<fund_id>', views.update_fund, name='update_fund'),
    path('delete/<fund_id>', views.delete_fund, name='delete_fund'),

    path('favorite/<fund_id>', views.favorite_fund, name='favorite_fund'),

    path('review/<fund_id>', views.add_review, name='add_review'),
    path('review/delete/<review_id>', views.delete_review, name='delete_review'),

    path('add/member/<fund_id>', views.add_members, name='add_members'),
    path('delete/member/<member_username>/<fund_id>', views.delete_member, name='delete_member'),
]

dekher/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home_view, name='home_view')
]

dekher/main/models.py
from django.db import models

# Create your models here.

dekher/main/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from fund.models import Fund
# Create your views here.


def home_view(request: HttpRequest):

    funds = Fund.objects.filter(owner = request.user)
    return render(request, 'home.html', context={'funds': funds})

dekher/main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"> <!-- Bootstrap Icons -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>

        <!--  My Styles  -->
        <link rel="stylesheet" href="{% static 'styles/main_style.css' %}">
        <style>

            .star-rating {
                display: flex;
                flex-direction: row;
                gap: 5px;
                margin-left: 20px;
            }

            .star-rating input {
                display: none;
            }

            .star {
                cursor: pointer;

            }

            .star .bi-star-fill {
                display: none;
            }

            .star:hover .bi-star-fill,
            .star:hover ~ label .bi-star-fill,
            .star-rating input:checked ~ label .bi-star-fill {
                display: inline;
            }

            .star:hover .bi-star,
            .star:hover ~ label .bi-star,
            .star-rating input:checked ~ label .bi-star {
                display: none;
            }
        </style>
    </head>
    <body style="background-color: #c5edd6">
        <header>
            <div class="container d-flex justify-content-between align-items-center mt-5 pt-2">
                <div>
                    {% if not request.user.is_authenticated %}
                    <div class="btn-group btn-group-lg" role="group" aria-label="Call to action">
                        <a type="button" class="btn btn-default btn-lg" href="{% url 'accounts:sign_in' %}">Sign In</a>
                        <span class="btn-circle btn-or">or</span>
                        <a type="button" class="btn btn-default btn-lg" href="{% url 'accounts:register' %}">Sign Up</a>
                    </div>
                    {% else %}
                    <div>
                        <div class="nav-item dropdown me-3 me-lg-1 align-items-center">
                            <a data-bs-toggle="dropdown" class="{% if request.resolver_match.app_name == 'accounts' %} active {% endif %} nav-link d-flex dropdown-toggle hidden-arrow align-items-center" href="#">
                                <div class="d-flex">

                                {% if request.user.is_authenticated %}
                                <img src="{{ request.user.profile.avatar.url }}" class="rounded-circle" height="32" loading="lazy"/>
                                {% endif %}
                                <h3 class="d-none d-sm-block h-3 ms-1">
                                    {% if request.user.is_authenticated %}
                                    {{request.user.username}}
                                    {% else %}
                                    Log In
                                    {% endif %}
                                </h3>
                                </div>
                            </a>
                            <ul class="dropdown-menu">
                                {% if request.user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'accounts:log_out' %}?next={{request.path}}">Log Out</a></li>
                                <li><a class="dropdown-item " href="{% url 'accounts:profile_view' request.user.username %}">Account Settings</a></li>

                                {% else %}
                                <li><a class="dropdown-item" href="{% url 'accounts:register' %}?next={{request.path}}">Sign Up</a></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:sign_in' %}?next={{request.path}}">Sign In</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                    {% endif %}
                </div>

                <a class="navbar-brand text-end me-2" href="{% url 'main:home_view' %}">
                    <img src="{% static 'images/dekhrLogo.svg' %}" width="150" height="120">
                </a>

            </div>
        </header>

        {% if messages %}
        {% for message in messages %}
        <div role="alert" class="z-1 position-absolute d-flex justify-content-center align-items-between alert {{message.extra_tags}} rounded-3 ms-3 mt-3 me-3 align-items-center fade show animate__animated animate__bounceIn" style="width: 500px;">

            <div class="text-dark ">
                <div class="h6">{{message}}</div>
            </div>
            <div class="text-end">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>

        </div>
        {% endfor %}
        {% endif %}

        {% block main %}{% endblock %}

        <footer class="text-center text-lg-start text-muted mt-5">
            <hr>
            <!-- Section: Social media -->
            <section class="d-flex justify-content-center justify-content-evenly p-4 border-bottom">
                <!-- Left -->
                <div class="me-5 d-none d-lg-block">
                    <span>Get connected with us on social networks:</span>

                </div>
                <!-- Left -->

                <!-- Right -->
                <div class="">
                    <a href="" class="me-4 text-reset text-decoration-none">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a href="" class="me-4 text-reset text-decoration-none">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a href="" class="me-4 text-reset text-decoration-none">
                        <i class="fab fa-google"></i>
                    </a>
                    <a href="" class="me-4 text-reset text-decoration-none">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a href="" class="me-4 text-reset text-decoration-none">
                        <i class="fab fa-linkedin"></i>
                    </a>
                    <a href="" class="me-4 text-reset text-decoration-none">
                        <i class="fab fa-github"></i>
                    </a>
                    <a href="/" class="btn btn-primary">Rate Us Now</a>
                </div>

            </section>


            <!-- Section: Links  -->
            <section class="">
                <div class="container text-center text-md-start mt-5">

                    <div class="row mt-3">

                        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

                            <h6 class="text-uppercase fw-bold mb-4">
                                <i class="fas fa-gem me-3"></i>Dekher By HmzH
                            </h6>
                            <p>
                                Dekher is one of HmzH company products, this web app offers a service to manage funding groups for friends and families</p>
                        </div>

                        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                            <!-- useful Links -->
                            <h6 class="text-uppercase fw-bold mb-4">
                                Products
                            </h6>
                            <p>
                                <a href="" class="text-reset">Funds</a>
                            </p>
                            <p>
                                <a href="" class="text-reset">New Fund</a>
                            </p>
                            <p>
                                <a href="" class="text-reset">My Funds</a>
                            </p>

                        </div>
                        <!-- Grid column -->

                        <!-- Grid column -->
                        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                            <!-- Links -->
                            <h6 class="text-uppercase fw-bold mb-4">
                                Useful links
                            </h6>
                            <p>
                                <a href="" class="text-reset">All Funds</a>
                            </p>
                            <p>
                                <a href="/#join-us" class="text-reset">Join EchoFund</a>
                            </p>
                            <p>
                                <a href="/#how_it_works" class="text-reset">How it works</a>
                            </p>
                            <p>
                                <a href="/#faq" class="text-reset">Help</a>
                            </p>
                        </div>

                        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                            <!-- contacts -->
                            <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                            <p><i class="fas fa-home me-3"></i> Riyadh, Qortoba 23523, KSA</p>
                            <p>
                                <i class="fas fa-envelope me-3"></i>
                                hmzh@support.com
                            </p>
                            <p><i class="fas fa-phone me-3"></i> +966 544581821</p>
                            <p><i class="fas fa-print me-3"></i> +966 544581821</p>
                        </div>
                        <!-- Grid column -->
                    </div>
                    <!-- Grid row -->
                </div>
            </section>
            <!-- Section: Links  -->

            <!-- Copyright -->
            <div class="text-center p-4 bg-dark text-light">
                <i class="bi bi-c-circle"></i> 2024 Copyright:
                <a class="text-light fw-bold" href="/">HmzH.com</a>
            </div>
            <!-- Copyright -->
        </footer>
    </body>
</html>

dekher/main/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block main %}
<main>
    <div class="container">
        <div class="top">
            {% if request.user.is_authenticated %}
                <div class="user_funds">
                    <h3>Funds</h3>
                    {% include 'fund_card.html' %}

                </div>
            {% endif %}
            <div class="row mt-5 mb-5">

                <img class="col-lg-6" src="{% static 'images/home-phone.png' %}">
                <div class="col-lg-6">
                    <div class="d-flex flex-column gap-5 ">
                        <strong class=" display-1 text-end mt-5 pt-5 text-success">ابق دائمًا ملتزماً بخطتك معنا</strong>
                        <div class="text-end align-items-center">

                            <a href="#more" class="btn btn-success">اعرف المزيد</a>
                        </div>
                    </div>
                </div>
            </div>

            <div id="more" class="container text-center mt-5 pt-5">
                <p class="display-1 m-3 mb-3 text-success">شركة دِخر هي شركة ناشئة تتطّلع إلى تغيير طريقة الإدخار بين الناس</p>
                <br><br>
                <h3 class="m-3 pt-4">صُمم موقعنا الإلكتوني لإدارة  الجمعيات المالية بين الناس وبنائها وتنميتها، مع الأشخاص الذين تعرفهم والأشخاص الذين تثق بهم. مع وجود العديد من الخدمات المماثلة، فإن الفريق خلف شركة دِخر يعمل بكد لتصميم الموقع الإلكتروني الذي تحتاج إليه</h3>
            </div>

            <div class="row mt-5 mb-5 pt-3">

                <img class="col-lg-6" src="{% static 'images/home-phone.png' %}">
                <div class="col-lg-6">
                    <div class="d-flex flex-column gap-5 ">
                        <strong class=" display-1 text-end mt-5 pt-5 text-success">إدخر مع الأصدقاء والعائلة</strong>
                        <h3 class="text-end">استخدم الموقع الإلكتروني لإنشاء الجمعية وإدارتها ودعوة الأعضاء بلا حدود.

                            يمكن للمستخدمين الإطلاع على تفاصيل الجمعية المشاركين فيها.</h3>
                    </div>
                </div>
            </div>

            <div class="row mt-5 mb-5 pt-3">

                <div class="col-lg-6">
                    <div class="d-flex flex-column gap-5 ">
                        <strong class=" display-1 text-end mt-5 pt-5 text-success">ابقَ على إطلاع</strong>
                        <h3 class="text-end">يستعرض الموقع كافة المعلومات المتعلقة بالمدفوعات الشهرية والشهر المحدد للقبض.
                            فإن شاشة العرض المُتضمنة ستغيّر طريقة تعاملك مع الجمعيات المالية.</h3>
                    </div>
                </div>
                <img class="col-lg-6" src="{% static 'images/home-phone.png' %}">
            </div>

            <div class="row mt-5 mb-5 pt-3">

                <img class="col-lg-6" src="{% static 'images/home-phone.png' %}">
                <div class="col-lg-6">
                    <div class="d-flex flex-column gap-5 ">
                        <strong class=" display-1 text-end mt-5 pt-5 text-success">ابني جمعيتك المالية</strong>
                        <h3 class="text-end">يقدم لك تطبيق دخر الخدمات والمساحات التي قد تثير اهتمامك.
                            يمكنك استخدام هذه الخدمات لإدارة أعضاء جدد والتفاعل معهم وبناء علاقات مالية معهم.</h3>
                    </div>
                </div>
            </div>

            <div class="d-flex justify-content-between p-5 mt-5 pt-5">

                <div class="text-end align-items-end">
                    <img src="{% static 'images/dekhrLogo.svg' %}" class="w-50">
                </div>

                <div class="col text-end">
                    <div class="">
                        <h1 class="">التواصل</h1>
                        <p class="">0544581821 <i class="bi bi-phone-fill"></i></p>
                        <p class="">شارع التحلية, جدة, السعودية <i class="bi bi-geo-alt-fill"></i></p>
                        <p class="">dekher@support.com <i class="bi bi-envelope-fill"></i></p>
                        <div class="text-end">
                            <i class="bi bi-instagram"></i>
                            <i class="bi bi-facebook"></i>
                            <i class="bi bi-twitter"></i>
                            <i class="bi bi-linkedin"></i>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</main>

{% endblock %}