dekher/accounts/urls.py
from . import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('signin/', views.sign_in, name="sign_in"),
    path('register/', views.register, name="register"),
    path('logout/', views.log_out, name="log_out"),

    path('profile/<user_name>', views.profile_view, name="profile_view"),
    path('profile/update/<user_name>', views.update_profile, name="update_profile"),
]

dekher/dekher/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('funds/', include('fund.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dekher/fund/urls.py
from . import views
from django.urls import path

app_name = 'fund'

urlpatterns = [
    path('add/', views.add_fund, name='add_fund'),
    path('complete/<fund_id>', views.complete_fund, name='complete_fund'),
    path('<fund_id>/details/', views.fund_details, name='fund_details'),

    path('update/<fund_id>', views.update_fund, name='update_fund'),
    path('delete/<fund_id>', views.delete_fund, name='delete_fund'),

    path('favorite/<fund_id>', views.favorite_fund, name='favorite_fund'),

    path('review/<fund_id>', views.add_review, name='add_review'),
    path('review/delete/<review_id>', views.delete_review, name='delete_review'),

    path('add/member/<fund_id>', views.add_members, name='add_members'),
    path('delete/member/<member_username>/<fund_id>', views.delete_member, name='delete_member'),
]

dekher/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home_view, name='home_view')
]

dekher/accounts/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.TextField(blank=True)
    phone_num = models.CharField(max_length=10, default='None')
    avatar = models.ImageField(upload_to='images/avatars', default='images/avatars/profileAvatar.jpg')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} Profile"

dekher/accounts/views.py
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.models import User
from django.db import transaction, IntegrityError
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest
from .models import Profile
from fund.models import Fund, Favorite

# Create your views here.
def register(request: HttpRequest):
    if request.method == "POST":
        try:
            with transaction.atomic():
                new_user = User.objects.create_user(
                    first_name = request.POST['first_name'],
                    last_name = request.POST['last_name'],
                    email = request.POST['email'],
                    password = request.POST['password'],
                    username = request.POST['username'],
                )
                new_user.save()

                profile = Profile(
                    user = new_user,
                    about = request.POST['about'],
                    avatar = request.FILES.get("avatar", Profile._meta.get_field("avatar").get_default()),
                )

                profile.save()

            messages.success(request, f'{new_user.username} Account was created Successfully', 'alert-success')
            return redirect('accounts:sign_in')
        except IntegrityError as ie:
            print(ie)
            messages.error(request, 'This username is taken, please try another one', 'alert-danger')
        except Exception as e:
            print(e)
            messages.error(request, 'error in creating your account', 'alert-danger')
    return render(request, 'login_form.html')


def sign_in(request: HttpRequest):

    if request.method == "POST":
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user:
            login(request, user)
            messages.success(request, f'{user.username} Signed in Successfully', 'alert-success')
            return redirect(request.GET.get('next', '/'))
        else:
            messages.error(request, 'Username or password is wrong, please try again', 'alert-danger')
    return render(request, 'login_form.html')


def log_out(request: HttpRequest):

    logout(request)
    messages.success(request, 'logged out successfully, See You later', 'alert-success')
    return redirect('main:home_view')


def profile_view(request: HttpRequest, user_name):

    if not request.user.is_authenticated:
        messages.error(request, 'Please Sign in to View Your Profile', 'alert-danger')
        return redirect('accounts:sign_in')

    user = User.objects.get(username=user_name)
    favorite_funds = Favorite.objects.filter(user = user)

    if not Profile.objects.filter(user = user).first():
        new_profile = Profile(user=user)
        new_profile.save()
    profile: Profile = user.profile
    # profile = Profile.objects.get(user=user)
    user_funds = Fund.objects.filter(owner=user)

    if request.method == "GET" and 'status' in request.GET and request.GET['status'] != 'all':
        user_funds = user_funds.filter(status = request.GET['status'])

        return render(request, 'profile.html', context={'user':user, 'status_choices': Fund.Status.choices, 'funds': user_funds})

    return render(request, 'profile.html', context={'user':user, 'status_choices': Fund.Status.choices, 'funds': user_funds, 'favorite_funds':favorite_funds})


def update_profile(request: HttpRequest, user_name):

    if not request.user.is_authenticated:
        messages.error(request, "Sign in to update your profile","alert-warning")
        return redirect("accounts:sign_in")

    user = User.objects.get(username=user_name)
    user_profile = Profile.objects.get(user=user)

    if request.method == "POST":
        try:
            with transaction.atomic():

                user_profile.about = request.POST['about']
                user_profile.phone_num = request.POST['phone_num']
                if 'avatar' in request.FILES: user_profile.avatar = request.FILES['avatar']

                user.first_name = request.POST['first_name']
                user.last_name = request.POST['last_name']
                user.username = request.POST['username']
                user.email = request.POST['email']

                user_profile.save()
                user.save()

                messages.success(request, 'Profile was Updated Successfully', 'alert-success')
                return redirect('accounts:profile_view', user_name=user.username)

        except Exception as e:
            print(e.__class__)
            messages.error(request, 'error in updating your profile ', 'alert-danger')
            return redirect('accounts:profile_view', user_name=user.username)

dekher/accounts/templates/login_form.html
{% extends 'base.html' %}

{% block title %}Sign In{% endblock %}

{% block main  %}
<main>
    <div class="container pt-4">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'main:home_view' %}" class="text-primary">Home</a></li>
                {% if request.resolver_match.view_name == 'accounts:register' %}
                <li class="breadcrumb-item active">Sign Up</li>
                {% else %}
                <li class="breadcrumb-item active">Sign In</li>
                {% endif %}
            </ol>
        </nav>
        <div class="container pt-5 mt-5 mb-5 pb-5 shadow rounded ">
            {% if request.resolver_match.view_name == 'accounts:register' %}
            <h3 class="text-center display-4">Sign Up</h3>
            <form class="m-5 p-5" action="{% url 'accounts:register' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}


                <div class="mb-3">
                    <label for="first_name" class="form-label">First name <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" name="first_name" id="first_name">
                    <label for="last_name" class="form-label">Last name</label>
                    <input type="text" class="form-control" name="last_name" id="last_name">
                </div>
                <div class="mb-3">
                    <label for="username" class="form-label">Username</label>
                    <input type="text" name="username" class="form-control" id="username">
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Email address</label>
                    <input type="email" class="form-control" name="email" id="email" aria-describedby="emailHelp">
                    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                </div>

                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" name='password' class="form-control" id="password">
                </div>
                <div class="mb-3">
                    <label for="avatar" class="form-label">Profile avatar</label>
                    <input id="avatar" type="file" class="form-image" name="avatar" accept="image/*" value="Avatar">
                </div>
                <div class="mb-3">
                    <label for="username" class="form-label">About</label>
                    <textarea name="about" class="form-control" id="about"></textarea>
                </div>
                <div class="mb-3 d-flex justify-content-between">
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="check">
                        <label class="form-check-label" for="check">Remember Me</label>
                    </div>
                    <a href="{% url 'accounts:sign_in' %}">Already Have An Account</a>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>

            {% else %}

            <h3 class="text-center display-4">Sign In</h3>
            <form class="m-5 p-5" action="{% url 'accounts:sign_in' %}{% if 'next' in request.GET %}?next={{request.GET.next}}{% endif %}" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="sign_in_username" class="form-label">Username</label>
                    <input type="text" class="form-control" name="username" id="sign_in_username">
                </div>
                <div class="mb-3">
                    <label for="sign_in_password" class="form-label">Password</label>
                    <input type="password" class="form-control" name="password" id="sign_in_password">
                </div>
                <div class="mb-3  d-flex justify-content-between">
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="sign_in_check">
                        <label class="form-check-label" for="sign_in_check">Remember Me</label>
                    </div>

                    <a href="{% url 'accounts:register' %}">Don't Have An Account</a>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            {% endif %}
        </div>
    </div>
</main>
{% endblock %}

dekher/accounts/templates/profile.html
{% extends 'base.html' %}
{% block title %} {{user.username}} Profile {% endblock %}

{% block main %}
<main class="my-5 mt-5 pt-5">
    <div class="container pb-3 mb-3">
        <nav class="ms-2" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'main:home_view' %}" class="text-primary">Home</a></li>
                <li class="breadcrumb-item"><a href="#" class="text-primary">User</a></li>
                <li class="breadcrumb-item active">User Profile</li>
            </ol>
        </nav>

        <div class="row g-4 mt-4">
            <div class="row">
                <!-- Profile Section -->
                <div class="col-md-4 col-lg-4">
                    <div class="card border-0 shadow-lg mb-sm-4 rounded-4 animate__animated animate__fadeInLeft">
                        <div class="card-header bg-secondary text-white text-center">
                            <h4 class="mb-0">Profile</h4>
                        </div>
                        <div class="card-body text-center p-4">
                            <!-- Logo -->
                            <div class="mb-4">
                                <img src="{{ user.profile.avatar.url }}" alt="User Avatar"
                                     class="img-fluid rounded-circle shadow-lg"
                                     style="max-width: 150px; height: 150px; object-fit: cover;">
                            </div>

                            <!-- Organization Details -->
                            <h5 class="card-title">@{{ user.username }}</h5>
                            <p class="text-muted">{{ user.first_name }} {{ user.last_name }}</p>
                            <div class="border rounded m-3 p-2">
                                <p class="text-center align-items-center">Bio:</p>
                                <hr>
                                <p class="text-muted">{{ user.profile.about }}</p>
                            </div>

                            <p class="text-muted">Since: {{ user.profile.created_at }}</p>


                            <!-- Edit Button -->
                            {% if request.user == user %}
                            <div class="mt-3">
                                <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editProfileModal">Edit Profile</button>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="col-md-8">

                    <!-- Editable Details Section -->
                    <div class="card shadow-lg animate__animated animate__fadeInRight">
                        <div class="card-body">
                            <div class="row mb-3">
                                <div class="col-sm-4"><strong>Name</strong></div>
                                <div class="col-sm-8">{{ user.username }}</div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-4"><strong>Description</strong></div>
                                <div class="col-sm-8">{{ user.profile.about }}</div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-4"><strong>Email</strong></div>
                                <div class="col-sm-8">{{ user.email }}</div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-4"><strong>Phone</strong></div>
                                <div class="col-sm-8">{{ user.profile.phone_num }}</div>
                            </div>

                        </div>
                    </div>

                    <!-- Funds Section -->
                    <div class="card shadow-lg rounded-4 my-4 animate__animated animate__fadeInUp" id="skills-info" style="display: block;">
                        <div class="card-body">
                            <div class="d-flex justify-content-between">
                                <h4 class="d-flex align-items-center gap-2 mb-3">
                                    <i class="bi bi-tools"></i>{% if request.user == user %}My {% else %} User {% endif %} Funds
                                </h4>
                                {% if request.user == user %}
                                <div class="d-flex flex-row gap-3 justify-content-between">

                                    <form class="" action="{% url 'accounts:profile_view' request.user.username %}"  method="get">
                                        <select name="status" onchange="this.form.submit()">
                                            <option>Select Status</option>
                                            <option value="all">All</option>
                                            {% for value, label in status_choices %}
                                            <option value="{{ value }}">{{ label }}</option>
                                            {% endfor %}
                                        </select>

                                    </form>

                                        <a href="{% url 'fund:add_fund' %}" class="text-dark">
                                            <span class="bi bi-plus-circle-fill" style="font-size: 1.6rem;"></span>
                                        </a>
                                </div>
                                </div>
                                {% endif %}
                            <div>
                                {% include 'fund_card.html' %}
                            </div>
                        </div>
                    </div>

                    <!-- Favorite funds Section -->
                    {% if request.user == user %}
                    <div class="row mb-3">
                        <div class="col">
                            <div class="card shadow-lg rounded-4 animate__animated animate__fadeInUp">
                                <div class="card-body">
                                    <div class="d-flex flex-row justify-content-between">
                                        <h4 class="d-flex align-items-center gap-2 mb-3">
                                            <i class="bi bi-heart-fill text-danger"></i>Favorite Funds
                                        </h4>

                                    </div>


                                    <div class="row">
                                        {% for x in favorite_funds %}
                                        <a class="text-decoration-none hover" href="{% url 'fund:fund_details' x.fund.id %}">
                                        <div class="col-md-4 mb-3">
                                            <div class="card">
                                                <div class="card-body">
                                                    <h5 class="card-title">{{ x.fund.name }}</h5>
                                                    <hr>
                                                    <p class="card-text">About: {{ x.fund.description }}</p>
                                                    <p class="card-text">Created At: {{ x.fund.created_at }}</p>

                                                </div>
                                            </div>
                                        </div>
                                        </a>
                                        {% empty %}
                                        <p>No Favorite Funds available yet.</p>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>


            <!-- Modal for Editing Profile -->
            <div class="modal fade" id="editProfileModal" tabindex="-1" aria-labelledby="editProfileModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="editProfileModalLabel">Edit Profile</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form method="post" action="{% url 'accounts:update_profile' user %}" enctype="multipart/form-data">
                                {% csrf_token %}

                                <label for="username" class="form-label">Username</label>
                                <input class="form-control" type="text" value="{{user.username}}" name="username" id="username">

                                <label for="first_name" class="form-label">First Name</label>
                                <input class="form-control" type="text" value="{{user.first_name}}" name="first_name" id="first_name">

                                <label for="last_name" class="form-label">Last Name</label>
                                <input class="form-control" type="text" value="{{user.last_name}}" name="last_name" id="last_name">

                                <label for="about" class="form-label">Bio</label>
                                <input class="form-control" type="text" value="{{user.profile.about}}" name="about" id="about">

                                <label for="email" class="form-label">Email</label>
                                <input class="form-control" type="email" value="{{user.email}}" name="email" id="email">

                                <label for="phone_num" class="form-label">Phone Number</label>
                                <input class="form-control" type="text" value="{{user.profile.phone_num}}" name="phone_num" id="phone_num">

                                <img id="imgPreview" src="{{ user.profile.avatar.url }}" class="img-thumbnail">
                                <input class="form-control" type="file"  name="avatar" accept="image/*" onchange="loadFile(event)">
                                <script>
                                    var loadFile = function(event) {
                                    var imgPreview = document.getElementById('imgPreview');
                                    imgPreview.src = URL.createObjectURL(event.target.files[0]);
                                    imgPreview.onload = function() {
                                        URL.revokeObjectURL(imgPreview.src) // free memory
                                    }
                                    };
                                </script>


                                <button type="submit" class="btn btn-primary">Save Changes</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
    </div>
</main>
{% endblock %}