dekher/accounts/urls.py
from . import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('signin/', views.sign_in, name="sign_in"),
    path('register/', views.register, name="register"),
    path('logout/', views.log_out, name="log_out"),

    path('profile/<user_name>', views.profile_view, name="profile_view"),
    path('profile/update/<user_name>', views.update_profile, name="update_profile"),
]

dekher/dekher/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('funds/', include('fund.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dekher/fund/urls.py
from . import views
from django.urls import path

app_name = 'fund'

urlpatterns = [
    path('add/', views.add_fund, name='add_fund'),
    path('complete/<fund_id>', views.complete_fund, name='complete_fund'),
    path('<fund_id>/details/', views.fund_details, name='fund_details'),

    path('update/<fund_id>', views.update_fund, name='update_fund'),
    path('delete/<fund_id>', views.delete_fund, name='delete_fund'),

    path('favorite/<fund_id>', views.favorite_fund, name='favorite_fund'),

    path('review/<fund_id>', views.add_review, name='add_review'),
    path('review/delete/<review_id>', views.delete_review, name='delete_review'),

    path('add/member/<fund_id>', views.add_members, name='add_members'),
    path('delete/member/<member_username>/<fund_id>', views.delete_member, name='delete_member'),
]

dekher/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home_view, name='home_view')
]

dekher/fund/models.py
from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Fund(models.Model):

    class Status(models.TextChoices):
        NEW = "new", "New"
        FINISHED = "finished", "Finished"
        IN_PROGRESS = "inProgress", "In Progress"
        PREPARING = "preparing", "Preparing"
        CANCELED = "canceled", "Canceled"

    name = models.CharField(max_length=50)
    description = models.TextField()
    monthly_stock = models.SmallIntegerField(default=1000)
    logo = models.ImageField(upload_to='images/logos', default='images/logos/fundLogo.jpg')

    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='fund_owner')
    members = models.ManyToManyField(User, related_name='fund_members', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    start_date = models.DateField(default=timezone.now, null=True)
    status = models.CharField(default=Status.NEW, choices=Status.choices, max_length=11)


class Favorite(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fund = models.ForeignKey(Fund, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class Review(models.Model):

    class Rates(models.IntegerChoices):

        STAR1 = 1, 'One Star'
        STAR2 = 2, 'Two Stars'
        STAR3 = 3, 'Three Stars'
        STAR4 = 4, 'Four Stars'
        STAR5 = 5, 'Five Stars'

    fund = models.ForeignKey(Fund, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.SmallIntegerField(choices=Rates.choices)
    comment = models.TextField()
    reviewed_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} on {self.fund.fund_name}"

dekher/fund/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from fund.models import Fund, Favorite, Review


# Create your views here.
def add_fund(request: HttpRequest):

    new_fund = Fund(
        owner = request.user,
        name = 'NewFund',
        description = f'New fund created by {request.user.username}',
        monthly_stock = 1000,

    )
    new_fund.save()
    return render(request, 'add_fund.html', context={'fund': new_fund})


def complete_fund(request: HttpRequest, fund_id):

    if request.method == "GET" and 'cancel' in request.GET:
        fund = Fund.objects.get(pk=fund_id)
        fund.delete()
        messages.success(request, 'Canceled successfully', 'alert-success')
        return redirect('accounts:profile_view', user_name = request.user.username)

    if request.method == "POST":
        fund = Fund.objects.get(pk=fund_id)

        if 'logo' in request.FILES: fund.logo = request.FILES['logo']
        fund.name = request.POST['name']
        fund.description = request.POST['description']
        fund.monthly_stock = request.POST['monthly_stock']
        fund.start_date = request.POST['start_date']
        fund.status = request.POST['status']

        fund.save()
        messages.success(request, 'Fund was created successfully', 'alert-success')
    return redirect('accounts:profile_view', user_name = request.user.username)


def fund_details(request: HttpRequest, fund_id):
    fund = Fund.objects.get(pk=fund_id)
    reviews = Review.objects.filter(fund=fund)
    favorite = Favorite.objects.filter(fund=fund, user=request.user)
    return render(request, 'fund_details.html', context={'fund': fund, 'reviews': reviews, 'rates': Review.Rates.choices, 'favorite': favorite})


def update_fund(request: HttpRequest, fund_id):

    fund = Fund.objects.get(pk=fund_id)

    if not request.user == fund.owner:
        messages.error(request, 'Only fund Owner can Edit fund data', 'alert-danger')
        return redirect('fund:fund_details', fund_id=fund_id)

    if request.method == "POST":
        if 'logo' in request.FILES: fund.logo = request.FILES['logo']
        fund.name = request.POST['name']
        fund.description = request.POST['description']
        fund.monthly_stock = request.POST['monthly_stock']
        fund.start_date = request.POST['start_date']
        fund.status = request.POST['status']
        fund.save()

        messages.success(request, 'Fund was Updated successfully', 'alert-success')
        return redirect('fund:fund_details', fund_id = fund_id)

    return render(request, 'update_fund.html', context={'fund': fund})


def delete_fund(request: HttpRequest, fund_id):

    fund = Fund.objects.get(pk=fund_id)
    fund.delete()
    messages.success(request, 'Fund Was Deleted Successfully', 'alert-success')
    return redirect('accounts:profile_view', user_name = request.user.username)


def favorite_fund(request: HttpRequest, fund_id):
    if not request.user.is_authenticated:
        messages.error(request, 'Please register to favorite funds', 'alert-danger')
        return redirect('accounts:sign_in')

    try:
        fund = Fund.objects.get(pk=fund_id)

        new_favorite = Favorite(
            user = request.user,
            fund = fund
        )
        favorite = Favorite.objects.filter(fund=fund, user=request.user)

        if not favorite:
            new_favorite.save()
            messages.success(request, 'fund added to favorite', 'alert-success')
        else:
            favorite.delete()
            messages.success(request, 'fund removed from favorite', 'alert-warning')

    except Exception as e:
        print(e)

    return redirect(request.GET.get('next', '/'))


def add_review(request: HttpRequest, fund_id):

    try:
        if not request.user.is_authenticated:
            messages.error(request, "Please Login to add reviews", 'alert-danger')
            return redirect('accounts:sign_in')
        if request.method == 'POST':
            new_comment = Review(
                fund=Fund.objects.get(pk=fund_id),
                user=request.user,
                comment=request.POST['comment'],
                rating=request.POST['rating'])
            new_comment.save()

            # # Send message to user
            # new_user_message = UserMessage(
            #     sender = User.objects.get(pk=1),
            #     user = request.user,
            #     subject = 'Review Fund',
            #     content = 'You Reviewed a Fund',
            # )

            # new_user_message.save()
            messages.success(request, 'Comment was added successfully', 'alert-success')
        return redirect('fund:fund_details', fund_id = fund_id)
    except Exception as e:
        messages.error(request, 'Error in adding your comment', 'alert-danger')
        # return render(request,'page_not_found.html')
        print(e)
        return redirect('fund:fund_details', fund_id = fund_id)


def delete_review(request: HttpRequest, review_id):

    if request.user.is_superuser:
        review = Review.objects.get(pk=review_id)
        review.delete()

        # Send message to user
        # new_user_message = UserMessage(
        #     sender = User.objects.get(pk=1),
        #     user = request.user,
        #     subject = 'Delete Review',
        #     content = 'You Deleted your review',
        # )
        #
        # new_user_message.save()

        messages.success(request, 'Review Deleted Successfully', 'alert-success')
    return redirect('fund:fund_details', fund_id=review.fund.id)


# TODO Add Members to funds using email or phone number
def add_members(request:HttpRequest, fund_id):

    if request.method == "POST":
        user_email = request.POST['member_email']
    fund = Fund.objects.get(pk = fund_id)
    try:
        user = User.objects.get(email=user_email)
    except Exception as e:
        print(e.__cause__, e.__class__, e.__traceback__)
        messages.error(request,'Only Dekher Members can be added to funds, please let them register to be added to your fund', 'alert-warning')
        return redirect('fund:fund_details', fund_id = fund_id)

    if not request.user == fund.owner:
        messages.error(request, "Register to Participate in Funds", 'alert-danger')
        return redirect('accounts:sign_in')
    try:
        fund.members.add(user)
        messages.success(request, 'Member was Added Successfully', 'alert-success')
        return redirect('fund:fund_details', fund_id = fund_id)
    except Exception as e:
        print(e.__cause__, e.__traceback__)
        messages.error(request, 'Error adding member. This member might be already added', 'alert-danger')
        return redirect('fund:fund_details', fund_id = fund_id)


def delete_member(request: HttpRequest, member_username, fund_id):

    try:
        fund = Fund.objects.get(pk = fund_id)
        user = User.objects.get(username = member_username)

        if user in fund.members.all():  # Check if the user is a member
            fund.members.remove(user)

            messages.success(request, 'Member was removed successfully', 'alert-success')
        return redirect('fund:update_fund', fund_id = fund_id)
    except Exception as e:
        print(e.__class__)
        messages.error(request, 'Error Deleting member', 'alert-danger')
        return redirect('fund:update_fund', fund_id = fund_id)

dekher/fund/templates/add_fund.html
{% extends 'base.html' %}

{% block title %}New Fund{% endblock %}

{% block main %}

<main>
    <div class="container shadow mt-3">
    <form class="d-flex flex-column gap-3 pt-4 ps-4 pe-4 pb-sm-1 rounded " action="{% url 'fund:complete_fund' fund.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

            <img src="{{ fund.logo.url }}" class="img-thumbnail w-25 text-center">
            <input type="file" name="logo" accept="image/*">

        <label class="form-label" for="fund_name">Fund Name</label>
        <input class="form-control" id="fund_name" name="name" type="text" value="{{fund.name}}" maxlength="50">

        <label class="form-label" for="description">Fund Description</label>
        <input class="form-control" id="description" name="description" type="text" value="{{fund.description}}">

        <label class="form-label" for="monthly_stock">Fund's Monthly Stock</label>
        <input class="form-control" id="monthly_stock" name="monthly_stock" type="text" value="{{fund.monthly_stock}}">

        {% for member in fund.members.all %}
        <p>{{ member.name }}</p>
        {% endfor %}

        <label class="form-label">Start At: {{ fund.start_date }}</label>
        <input class="form-control" type="date" value="{{ fund.start_date|date:'Y-m-d' }}" name="start_date">

        <h5>s: {{fund.status.label}}</h5>
        <select name="status">

            {% for value, label in fund.Status.choices %}
                <option value="{{ value }}" {% if fund.status == value %}selected{% endif %}>{{ label }}</option>
            {% endfor %}
        </select>

        <small>Created At: {{ fund.created_at }}</small>

        <input type="submit" class="btn btn-success" value="Create Fund">

    </form>
        <form class="d-flex flex-column gap-3 pe-4 ps-4 pb-4 rounded " action="{% url 'fund:complete_fund' fund.id %}" method="get">
            <input type="hidden" name="cancel">
            <input type="submit" value="Cancel" class="btn btn-danger">
        </form>
    </div>
</main>
{% endblock %}

dekher/fund/templates/fund_card.html
{% load static %}
{% for fund in funds %}
<div class="col" style="min-width: 10rem;">
    <div class="card row m-5">
        <div class="position-relative">
            <img class="card-img-top" style="height: 150px; object-fit: cover;" src="http://res.cloudinary.com/d3/image/upload/c_scale,q_auto:good,w_1110/trianglify-v1-cs85g_cc5d2i.jpg" alt="Card background">
            <img class="position-absolute" style="width: 100px; height: 100px; object-fit: cover; bottom: -50px; left: 50%; transform: translateX(-50%); border: 5px solid white; border-radius: 50%;" src="{{ fund.logo.url }}" alt="Avatar">
        </div>
        <div class="card-body pt-2 mt-4">

            <div class="d-flex justify-content-between">
                {% if request.user == fund.owner %}
                <div>
                    <p class="btn btn-warning rounded-2 ps-2 pe-2">Enrolled</p>
                </div>
                {% endif %}
                <h6 class="text-end"> {{ fund.status }}</h6>
            </div>

            <div class="d-flex justify-content-between">

                <h4 class="">{{ fund.name|truncatechars:15 }}</h4>
                <p class="text-end">Created At: {{ fund.created_at|date:'Y-m-d' }}</p>
            </div>

            <p class="card-text"><i class="bi bi-cash text-success"></i> Stock: <img style="width: 1rem; height: 1rem" src="{% static 'images/Saudi_Riyal_Symbol.svg.png' %}"> {{ fund.monthly_stock }} Per Month</p>

            <p class="card-text">Start At: {{ fund.start_date|date:'d-m-Y' }}</p>


        </div>
        <div class="card-footer bg-transparent d-flex justify-content-between">
            <div>
                <a href="{% url 'fund:fund_details' fund.id %}" class="btn btn-success">Details</a>
            </div>
            <div>
                {% if not request.user == fund.owner and not request.user in fund.members.all %}
                <a href="" class="btn btn-outline-primary">Participate</a>
                {% endif %}
                {% if request.user == fund.owner %}
                    <a class="btn btn-warning" href="{% url 'fund:update_fund' fund.id %}"><i class="bi bi-pencil-square"></i></a>
                    <a class="btn btn-danger" href="{% url 'fund:delete_fund' fund.id %}"><i class="bi bi-trash"></i></a>
                {% endif %}
            </div>

        </div>
    </div>
</div>
{% endfor %}

dekher/fund/templates/fund_details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Fund Details{% endblock %}

{% block main %}
<main>
    <div class="container mt-5">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'main:home_view' %}" class="text-primary">Home</a></li>
                <li class="breadcrumb-item active">Fund Details</li>
            </ol>
        </nav>
        <h1 class="display-4 text-center p-3">Fund Details</h1>
        <div class="row  p-5 shadow rounded">

            <div class="col p-3 g-2">
                <div class="d-flex justify-content-between mb-4">
                    <div class="">
                        <h1 class="">{{fund.fund_name}}</h1>
                        <h6><i class="bi bi-calendar-date"></i> Start Date: {{ fund.start_date }}</h6>
                        <p class="card-text"><i class="fas fa-search pe-2"></i>{{ fund.about|truncatechars:30 }}</p>

                        <p class="card-text">Created By: <a href="{% url 'accounts:profile_view' fund.owner.username %}"> @{{ fund.owner }} </a></p>
                    </div>
                    <div>
                        {% if favorite %}
                        <a href="{% url 'fund:favorite_fund' fund.id %}?next={{request.path}}" class="text-end text-danger"> <i class="bi bi-heart-fill"></i></a>
                        {% else %}
                        <a href="{% url 'fund:favorite_fund' fund.id %}?next={{request.path}}" class="text-end text-danger"> <i class="bi bi-heart"></i></a>
                        {% endif %}



                    </div>

                </div>

                <h6>Description: </h6>
                <p>{{fund.description}}</p>

                <h6><i class="bi bi-cash pe-2 text-success" ></i> Monthly Stock: <img style="width: 1rem; height: 1rem" src="{% static 'images/Saudi_Riyal_Symbol.svg.png' %}">{{fund.monthly_stock}}</h6>
                {% if request.user == fund.owner %}
                <div class="d-flex gap-2 align-items-center mt-3">
                    <div class="dropdown">

                            <i class="dropdown-toggle bi bi-plus-circle-fill" style="font-size: 1.6rem;" data-bs-toggle="dropdown" aria-expanded="false"></i>

                        <ul class="dropdown-menu">
                            <li>
                                <form action="{% url 'fund:add_members' fund.id %}" method="post">
                                    {% csrf_token %}
                                    <label class="form-label" for="member_email">Member Email</label>
                                    <input class="form-control" id="member_email" type="text" name='member_email'>
                                    <button class="btn btn-success" type="submit">Add Member</button>
                                </form>
                            </li>

                        </ul>
                    </div>

                    <h4>Members [{{fund.members.all.count}}]:</h4>

                    {% for member in fund.members.all %}
                    <a href="{% url 'accounts:profile_view' member.username %}"><h5>@{{member.username}}</h5></a>
                    {% endfor %}
                </div>
                {% endif %}
                <div class="text-end">
                    {% if request.user == fund.owner %}
                    <a class="btn btn-warning" href="{% url 'fund:update_fund' fund.id %}"><i class="bi bi-pencil-square"></i></a>
                    <a class="btn btn-danger" href="{% url 'fund:delete_fund' fund.id %}"><i class="bi bi-trash"></i></a>

                    {% endif %}

                </div>

            </div>
        </div>
    </div>
    <div class="container mt-5 mb-5">
        {% if reviews %}
        <div class="container shadow p-5">
            <h2>Reviews ({{reviews.count}})</h2>
            {% for review in reviews %}
            <div class="p-5 shadow rounded mt-2 mb-5">
                <div class="d-flex gap-3 justify-content-center">
                    <h3>{{review.user.first_name}} {{review.user.last_name}}</h3>
                    <a href="{% url 'accounts:profile_view' review.user.username %}"><h5>@{{review.user.username}}</h5></a>
                </div>
                <p class="text-center">comment: {{review.comment}}</p>
                <div class="d-flex justify-content-between">
                    <div class="d-flex gap-3 align-items-center">
                        <p>Rating {{ review.rating }}</p>
                        {% for i in '12345'|make_list %}
                        {% if forloop.counter <= review.rating %}
                        <i class="bi bi-star-fill text-warning"></i>
                        {% else %}
                        <i class="bi bi-star text-warning"></i>
                        {% endif %}
                        {% endfor %}

                    </div>

                    <a href="{% url 'fund:delete_review' review.id %}"><i class="bi bi-trash"></i></a>
                </div>
                <p>{{review.reviewed_at}}</p>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        {% if request.user.is_authenticated %}
        <form class="d-flex flex-column gap-4 shadow rounded p-5 mt-5" action="{% url 'fund:add_review' fund.id %}" method="post">
            <h3 class="mt-4">Add new Review</h3>
            {% csrf_token %}
            <div>

                <label for="review" class="form-label">Your Comment</label>
                <textarea class="form-control" id="review" name="comment" required ></textarea>
            </div>

            <div class="">

                <div class="form-outline">

                    <p class="form-label">Rating: </p>
                    <div class="star-rating">
                        {% for rate, value in rates reversed %}

                        <input type="radio" id="star{{ rate }}" name="rating" value="{{ rate }}" required/>
                        <label for="star{{ rate }}" class="star">
                            <i class="bi bi-star text-warning"></i>
                            <i class="bi bi-star-fill text-warning"></i>
                        </label>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <input type="submit" name="Add">
        </form>
        {% else %}
        <div class="p-3 rounded bg-warning g-3 mt-3 d-flex flex-column gap-3">
            <p>Only Users can add comments</p>
            <a href="">Sign in to your account to add comments</a>
            <a href="">Or Create a New account now!</a>
        </div>
        {% endif %}
    </div>
</main>
{% endblock %}

dekher/fund/templates/update_fund.html
{% extends 'base.html' %}

{% block title %}Update Fund{% endblock %}

{% block main %}

<main>
    <div class="container shadow mt-3">
        <form class="d-flex flex-column gap-3 p-4 rounded " action="{% url 'fund:update_fund' fund.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <img src="{{ fund.logo.url }}" class="img-thumbnail w-25 text-center">
            <input type="file" name="logo" accept="image/*">

            <label class="form-label" for="fund_name">Fund Name</label>
            <input class="form-control" id="fund_name" name="name" type="text" value="{{fund.name}}" maxlength="50">

            <label class="form-label" for="description">Fund Description</label>
            <input class="form-control" id="description" name="description" type="text" value="{{fund.description}}">

            <label class="form-label" for="monthly_stock">Fund's Monthly Stock</label>
            <input class="form-control" id="monthly_stock" name="monthly_stock" type="text" value="{{fund.monthly_stock}}">

            <label class="form-label">Start At: {{ fund.start_date }}</label>
            <input class="form-control" type="date" value="{{ fund.start_date|date:'Y-m-d' }}" name="start_date">

            <h5>s: {{fund.status}}</h5>
            <select name="status">

                {% for value, label in fund.Status.choices %}
                <option value="{{ value }}" {% if fund.status == value %}selected{% endif %}>{{ label }}</option>
                {% endfor %}
            </select>
            {% for member in fund.members.all %}
            <p>{{ member.username }} <a href="{% url 'fund:delete_member' member.username fund.id  %}"><i class="bi bi-trash text-danger"></i></a></p>
            {% endfor %}
            <small>Created At: {{ fund.created_at }}</small>

            <input type="submit" class="btn btn-success" value="Save changes">
        </form>
    </div>
</main>
{% endblock %}